server:
  servlet:
    context-path: /seller
  port: 8082

logging:
  level:
    com.googlecode.jsonrpc4j: debug
#rpc配置以/结尾    
rpc.manager.url:  http://localhost:8081/manager/
#rpc
#  client:
#    url:  http://localhost:8081/manager
#    basePackage: com.do1.api
spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss.SSS
#    time-zone: GMT+8
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://127.0.0.1:61616
    packages:
      trust-all: true
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/seller?user=root&password=123&useUnicode=true&characterEncoding=utf-8
    backup:
      url: jdbc:mysql://localhost:3306/seller-backup?user=root&password=123&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
swagger:
  basePackage: com.do1.seller.controller
  title: 销售端API
  description: >
    authId 是由本方提供给接口调用方用于安全控制及身份识别，请在需要此参数的接口上，通过请求头传递。
    sign 是接口调用方使用私钥对请求对象中的非空字段按字典排序之后的JSON字符串进行的签名。请在需要此参数的接口上，通过请求头传递。