spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss.SSS
#    time-zone: GMT+8
   
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=123&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: true
server:
  servlet:  
    context-path: /manager
  port: 8081
swagger:
  groupName: manger
  basePackage: com.do1.manager.controller

logging:
   level:
      com.googlecode.jsonrpc4j: debug